{
	"version": 1491220549,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/player-sheet0.png",
		"images/platforma-sheet0.png",
		"images/key-sheet0.png",
		"images/enemy-sheet0.png",
		"images/tiledbackground.png",
		"images/kluczsheet-sheet0.png",
		"media/pickup_coin.m4a",
		"media/pickup_coin.ogg",
		"media/hit_hurt3.m4a",
		"media/hit_hurt3.ogg",
		"media/click.m4a",
		"media/click.ogg",
		"media/music.m4a",
		"media/music.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}