{
	"version": 1495567110,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/9patch.png",
		"images/9patch2.png",
		"media/impulsedensehall.m4a",
		"media/impulsedensehall.ogg",
		"media/impulsespring.m4a",
		"media/impulsespring.ogg",
		"media/impulsetelephone.m4a",
		"media/impulsetelephone.ogg",
		"media/impulsewarehouse.m4a",
		"media/impulsewarehouse.ogg",
		"media/explosion 1.m4a",
		"media/explosion 1.ogg",
		"media/ricochet 1.m4a",
		"media/ricochet 1.ogg",
		"media/sfx1.m4a",
		"media/sfx1.ogg",
		"media/sfx5.m4a",
		"media/sfx5.ogg",
		"media/epicarpg.m4a",
		"media/epicarpg.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}