{
	"version": 1484781646,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/aimspot-sheet0.png",
		"images/peer-sheet0.png",
		"images/peerlaser-sheet0.png",
		"images/rock-sheet0.png",
		"images/tiledbackground2.png",
		"images/1371807442dbzbozlogo-sheet0.png",
		"images/goku_genkidama_by_ficdogg-sheet0.png",
		"images/hpbar-sheet0.png",
		"images/enbar-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/expbar-sheet0.png",
		"images/spritefontstr.png",
		"images/genki_dama_by_jinta2-sheet0.png",
		"images/genki_dama_by_jinta-sheet0.png",
		"images/kiblast-sheet0.png",
		"images/bigblast-sheet0.png",
		"images/explosionki-sheet0.png",
		"images/explosionki-sheet1.png",
		"images/ve-sheet0.png",
		"images/ve-sheet1.png",
		"images/ve-sheet2.png",
		"images/kiblast2-sheet0.png",
		"images/f_exp-sheet0.png",
		"images/f_exp-sheet1.png",
		"media/dragonball z sound effects (2).m4a",
		"media/dragonball z sound effects (2).ogg",
		"media/dragonball z sound effects (3).m4a",
		"media/dragonball z sound effects (3).ogg",
		"media/dragonball z sound effects (4).m4a",
		"media/dragonball z sound effects (4).ogg",
		"media/dragonball z sound effects hit.m4a",
		"media/dragonball z sound effects hit.ogg",
		"media/dragonball z sound effects (480p.38).m4a",
		"media/dragonball z sound effects (480p.38).ogg",
		"media/dragonball z sound effects (480p.big blast).m4a",
		"media/dragonball z sound effects (480p.big blast).ogg",
		"media/dragonball z sound effects (480p.kameha).m4a",
		"media/dragonball z sound effects (480p.kameha).ogg",
		"media/dragonball z sound effects (charge).m4a",
		"media/dragonball z sound effects (charge).ogg",
		"media/dragonball z.m4a",
		"media/dragonball z.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"c2mp-net.js",
		"c2mp-peer.js",
		"c2mp.js",
		"waker.js"
	]
}