{
	"version": 1491663347,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/sprite5-sheet0.png",
		"images/spaceshipspr2-sheet0.png",
		"images/1playership-sheet0.png",
		"images/spaceshipspr4gun-sheet0.png",
		"images/leftside-sheet0.png",
		"images/rightside-sheet0.png",
		"images/companionbody-sheet0.png",
		"images/1player-sheet0.png",
		"images/enemy-sheet0.png",
		"images/enemy-sheet1.png",
		"images/playerbullet-sheet0.png",
		"images/enemybullet-sheet0.png",
		"images/particles.png",
		"images/enemyshield-sheet0.png",
		"images/enemyarmor-sheet0.png",
		"images/enemyhp-sheet0.png",
		"images/firefxplayer-sheet0.png",
		"images/firefxplayer-sheet1.png",
		"images/firefxplayer-sheet2.png",
		"images/enemyshieldx-sheet0.png",
		"images/firefxenemy-sheet0.png",
		"images/firefxenemy-sheet1.png",
		"images/firefxenemy-sheet2.png",
		"images/blood-sheet0.png",
		"images/smoke-sheet0.png",
		"images/smoke-sheet1.png",
		"images/smoke-sheet2.png",
		"images/companionpathfind-sheet0.png",
		"images/companiondestination-sheet0.png",
		"images/generator-sheet0.png",
		"images/generator-sheet1.png",
		"images/companionshield-sheet0.png",
		"images/companionarmor-sheet0.png",
		"images/firefxcompanion-sheet0.png",
		"images/firefxcompanion-sheet1.png",
		"images/firefxcompanion-sheet2.png",
		"images/maxresdefault3-sheet0.png",
		"images/maxresdefault4-sheet0.png",
		"images/electric-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/corpse-sheet0.png",
		"images/corpse-sheet1.png",
		"images/doorleftmain-sheet0.png",
		"images/doorright-sheet0.png",
		"images/accescarditem-sheet0.png",
		"images/accescarditem-sheet1.png",
		"images/itemlight-sheet0.png",
		"images/tilemapground.png",
		"images/tilemapsolid.png",
		"images/box-sheet0.png",
		"images/box-sheet1.png",
		"images/component-sheet0.png",
		"images/component-sheet1.png",
		"images/sprite4-sheet0.png",
		"images/charge-sheet0.png",
		"images/evac-sheet0.png",
		"images/lens-sheet0.png",
		"images/spaceshipspr-sheet0.png",
		"images/space_background_blue_dots_73340_3840x-sheet0.png",
		"images/tiledbackground.png",
		"images/playerbulletspace-sheet0.png",
		"images/orangeship-sheet0.png",
		"images/orangeship-sheet1.png",
		"images/orangeship-sheet2.png",
		"images/light_-sheet0.png",
		"images/cel-sheet0.png",
		"images/blueflarepsd-sheet0.png",
		"images/y80ew2-sheet0.png",
		"images/y80ew2-sheet1.png",
		"images/spaceshipinfo.png",
		"images/interstellar-sheet0.png",
		"images/info_agent-sheet0.png",
		"images/info_agent-sheet1.png",
		"images/info_agent-sheet2.png",
		"images/tiledbackground2.png",
		"images/spacecloudpngp-sheet0.png",
		"images/spacecloudpngp-sheet1.png",
		"images/spacecloudpngp-sheet2.png",
		"images/enemyweapon-sheet0.png",
		"images/enemyweapon-sheet1.png",
		"images/enemyweapon-sheet2.png",
		"images/dmodscreens-sheet0.png",
		"images/info.png",
		"images/btnblue-sheet0.png",
		"images/btnblue-sheet1.png",
		"images/containerprefabsmall-sheet0.png",
		"images/device-sheet0.png",
		"images/3bron-sheet0.png",
		"images/1glowa-sheet0.png",
		"images/1glowa-sheet1.png",
		"images/slave-sheet0.png",
		"images/techaudio-sheet0.png",
		"images/btnbluetrain-sheet0.png",
		"media/167074__drminky__slime-death-1.m4a",
		"media/167074__drminky__slime-death-1.ogg",
		"media/40839__scuzzpuck__cutthroat.m4a",
		"media/40839__scuzzpuck__cutthroat.ogg",
		"media/76958__michel88__deathd.m4a",
		"media/76958__michel88__deathd.ogg",
		"media/76960__michel88__deathh.m4a",
		"media/76960__michel88__deathh.ogg",
		"media/76962__michel88__deaths.m4a",
		"media/76962__michel88__deaths.ogg",
		"media/76966__michel88__paind.m4a",
		"media/76966__michel88__paind.ogg",
		"media/76967__michel88__paine.m4a",
		"media/76967__michel88__paine.ogg",
		"media/76968__michel88__painh.m4a",
		"media/76968__michel88__painh.ogg",
		"media/76969__michel88__paino.m4a",
		"media/76969__michel88__paino.ogg",
		"media/76971__michel88__painr.m4a",
		"media/76971__michel88__painr.ogg",
		"media/76972__michel88__pains.m4a",
		"media/76972__michel88__pains.ogg",
		"media/76973__michel88__piggrunt1.m4a",
		"media/76973__michel88__piggrunt1.ogg",
		"media/cpu.m4a",
		"media/cpu.ogg",
		"media/cpu2.m4a",
		"media/cpu2.ogg",
		"media/ok.m4a",
		"media/ok.ogg",
		"media/opendoor.m4a",
		"media/opendoor.ogg",
		"media/pickupammo.m4a",
		"media/pickupammo.ogg",
		"media/shieldhit.m4a",
		"media/shieldhit.ogg",
		"media/yes.m4a",
		"media/yes.ogg",
		"media/pick2.m4a",
		"media/pick2.ogg",
		"media/pick3.m4a",
		"media/pick3.ogg",
		"media/pick4.m4a",
		"media/pick4.ogg",
		"media/pick5.m4a",
		"media/pick5.ogg",
		"media/pickup.m4a",
		"media/pickup.ogg",
		"media/fx_laser_impact_02_001.m4a",
		"media/fx_laser_impact_02_001.ogg",
		"media/soundscrate-scifi-laser1_001.m4a",
		"media/soundscrate-scifi-laser1_001.ogg",
		"media/soundscrate-scifi-laser2_001.m4a",
		"media/soundscrate-scifi-laser2_001.ogg",
		"media/soundscrate-scifi-laser3_001.m4a",
		"media/soundscrate-scifi-laser3_001.ogg",
		"media/soundscrate-scifi-laser4_001.m4a",
		"media/soundscrate-scifi-laser4_001.ogg",
		"media/soundscrate-scifi-laser5_001.m4a",
		"media/soundscrate-scifi-laser5_001.ogg",
		"media/laser1.m4a",
		"media/laser1.ogg",
		"media/laser3.m4a",
		"media/laser3.ogg",
		"media/lets go_001.m4a",
		"media/lets go_001.ogg",
		"media/cratebreak3.m4a",
		"media/cratebreak3.ogg",
		"media/armor.m4a",
		"media/armor.ogg",
		"media/shieldimpact.m4a",
		"media/shieldimpact.ogg",
		"media/hmm2_001.m4a",
		"media/hmm2_001.ogg",
		"media/hmm_001.m4a",
		"media/hmm_001.ogg",
		"media/armor upgrade.m4a",
		"media/armor upgrade.ogg",
		"media/health.m4a",
		"media/health.ogg",
		"media/shields upgrade.m4a",
		"media/shields upgrade.ogg",
		"media/ammo upgrade.m4a",
		"media/ammo upgrade.ogg",
		"media/charge.m4a",
		"media/charge.ogg",
		"media/magazine upgrade.m4a",
		"media/magazine upgrade.ogg",
		"media/step_metal_01.m4a",
		"media/step_metal_01.ogg",
		"media/step_metal_02.m4a",
		"media/step_metal_02.ogg",
		"media/step_metal_03.m4a",
		"media/step_metal_03.ogg",
		"media/step_metal_04.m4a",
		"media/step_metal_04.ogg",
		"media/step_metal_05.m4a",
		"media/step_metal_05.ogg",
		"media/far explosion.m4a",
		"media/far explosion.ogg",
		"media/sample alarm.m4a",
		"media/sample alarm.ogg",
		"media/shootammo.m4a",
		"media/shootammo.ogg",
		"media/bug crush 1.m4a",
		"media/bug crush 1.ogg",
		"media/bug crush 10.m4a",
		"media/bug crush 10.ogg",
		"media/bug crush 2.m4a",
		"media/bug crush 2.ogg",
		"media/bug crush 4.m4a",
		"media/bug crush 4.ogg",
		"media/bug crush 5.m4a",
		"media/bug crush 5.ogg",
		"media/bug crush 8.m4a",
		"media/bug crush 8.ogg",
		"media/game lil bug death.m4a",
		"media/game lil bug death.ogg",
		"media/new bonus 2.m4a",
		"media/new bonus 2.ogg",
		"media/end.m4a",
		"media/end.ogg",
		"media/level.m4a",
		"media/level.ogg",
		"media/score.m4a",
		"media/score.ogg",
		"media/trigger_click_001.m4a",
		"media/trigger_click_001.ogg",
		"media/58818__syna-max__not-funny-2.m4a",
		"media/58818__syna-max__not-funny-2.ogg",
		"media/hey.m4a",
		"media/hey.ogg",
		"media/lab ambient.m4a",
		"media/lab ambient.ogg",
		"media/sever ambience.m4a",
		"media/sever ambience.ogg",
		"media/voice-access-denied_001.m4a",
		"media/voice-access-denied_001.ogg",
		"media/cardlock-open.m4a",
		"media/cardlock-open.ogg",
		"media/accendenied.m4a",
		"media/accendenied.ogg",
		"media/space.m4a",
		"media/space.ogg",
		"media/relaxation loop.m4a",
		"media/relaxation loop.ogg",
		"media/singularity.m4a",
		"media/singularity.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"firebase.js",
		"pathfind.js"
	]
}