{
	"version": 1485556496,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/background-sheet0.png",
		"images/background-sheet1.png",
		"images/sprite-sheet0.png",
		"images/player-sheet0.png",
		"images/player-sheet1.png",
		"images/player-sheet2.png",
		"images/tiledbackground.png",
		"images/sprite3-sheet0.png",
		"images/cam-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/sprite5-sheet1.png",
		"images/ffloatingearth-sheet0.png",
		"images/meteor-sheet0.png",
		"images/meteor-sheet1.png",
		"images/exlplo-sheet0.png",
		"images/exlplo-sheet1.png",
		"images/spritefont.png",
		"images/arrow-sheet0.png",
		"images/arrow-sheet1.png",
		"images/arrow-sheet2.png",
		"images/rocket-sheet0.png",
		"images/powerup-sheet0.png",
		"images/powerup-sheet1.png",
		"images/powerup-sheet2.png",
		"images/ray-sheet0.png",
		"images/lens-sheet0.png",
		"images/smoke-sheet0.png",
		"images/charge2-sheet0.png",
		"images/charge2-sheet1.png",
		"images/charge2-sheet2.png",
		"images/meteorhw-sheet0.png",
		"media/mesage.m4a",
		"media/mesage.ogg",
		"media/tap.m4a",
		"media/tap.ogg",
		"media/laser1.m4a",
		"media/laser1.ogg",
		"media/far explosion.m4a",
		"media/far explosion.ogg",
		"media/alien button.m4a",
		"media/alien button.ogg",
		"media/shootammo.m4a",
		"media/shootammo.ogg",
		"media/soundscrate-scifi-laser2_001.m4a",
		"media/soundscrate-scifi-laser2_001.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"backendless.min.js",
		"moment-with-locales.min.js",
		"firebase.js",
		"animate.min.css"
	]
}