{
	"version": 1497709212,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/rustanim-sheet0.png",
		"images/rustanim-sheet1.png",
		"images/rustanim-sheet2.png",
		"images/rustmov-sheet0.png",
		"images/bob-sheet0.png",
		"images/bob-sheet1.png",
		"images/bob-sheet2.png",
		"images/bob-sheet3.png",
		"images/guzikeq-sheet0.png",
		"images/tlo-sheet0.png",
		"images/tlo-sheet1.png",
		"images/podpstrzalka-sheet0.png",
		"images/podpstrzalka-sheet1.png",
		"images/kropelka-sheet0.png",
		"images/kropelka-sheet1.png",
		"images/odlamki-sheet0.png",
		"images/odlamki2-sheet0.png",
		"images/odlamki2-sheet1.png",
		"images/drzwi-sheet0.png",
		"images/botlatajacy-sheet0.png",
		"images/drzwiczki-sheet0.png",
		"images/obiektypoz1-sheet0.png",
		"images/obiektypoz1-sheet1.png",
		"images/okna-sheet0.png",
		"images/glowa-sheet0.png",
		"images/rura-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/zebatka-sheet0.png",
		"images/zebatka-sheet1.png",
		"images/wiatraczek-sheet0.png",
		"images/wiatraczek-sheet1.png",
		"images/robaki-sheet0.png",
		"images/robaki-sheet1.png",
		"images/kolkropla-sheet0.png",
		"images/kolkropla-sheet1.png",
		"images/bolec-sheet0.png",
		"images/bolec-sheet1.png",
		"images/lampa-sheet0.png",
		"images/lampa-sheet1.png",
		"images/glowabad-sheet0.png",
		"images/nogibad-sheet0.png",
		"images/nogibad-sheet1.png",
		"images/klapabad-sheet0.png",
		"images/klapabad-sheet1.png",
		"images/bad2-sheet0.png",
		"images/bad2-sheet1.png",
		"images/bad2-sheet2.png",
		"images/bad2-sheet3.png",
		"images/bad2-sheet4.png",
		"images/bad2-sheet5.png",
		"images/bad2-sheet6.png",
		"images/bad2-sheet7.png",
		"images/bad2-sheet8.png",
		"images/bad2-sheet9.png",
		"images/bad2-sheet10.png",
		"images/bad2-sheet11.png",
		"images/badkorpus-sheet0.png",
		"images/introtlo-sheet0.png",
		"images/introtlo-sheet1.png",
		"images/1_-sheet0.png",
		"images/1_-sheet1.png",
		"images/1introeva-sheet0.png",
		"images/1introeva-sheet1.png",
		"images/introrust-sheet0.png",
		"images/ricintrolezy-sheet0.png",
		"images/ricintrolezy-sheet1.png",
		"images/ricintrolezy-sheet2.png",
		"images/sterowiec-sheet0.png",
		"images/tulow_-sheet0.png",
		"images/toster-sheet0.png",
		"images/toster-sheet1.png",
		"images/reka-sheet0.png",
		"images/reka2-sheet0.png",
		"images/restartbutton-sheet0.png",
		"images/restartbutton-sheet1.png",
		"images/kamera-sheet0.png",
		"images/guzikmenu-sheet0.png",
		"images/przyciemnienie.png",
		"images/target-sheet0.png",
		"images/strefachodzenia-sheet0.png",
		"images/sprite21-sheet0.png",
		"images/trescdymek-sheet0.png",
		"images/trescdymek-sheet1.png",
		"images/items-sheet0.png",
		"images/eqitem-sheet0.png",
		"images/sprite33-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/sprite4-sheet1.png",
		"images/sprite4-sheet2.png",
		"images/sprite17-sheet0.png",
		"images/sprite17-sheet1.png",
		"images/sprite19-sheet0.png",
		"images/sprite19-sheet1.png",
		"images/sprite20-sheet0.png",
		"images/sprite27-sheet0.png",
		"images/sprite35-sheet0.png",
		"images/sprite35-sheet1.png",
		"images/sprite37-sheet0.png",
		"images/sprite37-sheet1.png",
		"images/sprite37-sheet2.png",
		"images/sprite37-sheet3.png",
		"images/sprite37-sheet4.png",
		"images/sprite37-sheet5.png",
		"images/sprite37-sheet6.png",
		"images/sprite37-sheet7.png",
		"images/sprite38-sheet0.png",
		"images/sprite39-sheet0.png",
		"images/sprite39-sheet1.png",
		"images/sprite41-sheet0.png",
		"images/sprite42-sheet0.png",
		"images/sprite42-sheet1.png",
		"images/sprite43-sheet0.png",
		"images/sprite44-sheet0.png",
		"images/sprite45-sheet0.png",
		"images/sprite45-sheet1.png",
		"images/sprite46-sheet0.png",
		"images/sprite46-sheet1.png",
		"images/sprite48-sheet0.png",
		"images/sprite48-sheet1.png",
		"images/sprite49-sheet0.png",
		"images/sprite50-sheet0.png",
		"images/sprite54-sheet0.png",
		"images/sprite54-sheet1.png",
		"images/sprite55-sheet0.png",
		"images/sprite55-sheet1.png",
		"images/sprite55-sheet2.png",
		"images/drzwi2-sheet0.png",
		"images/dymek-sheet0.png",
		"images/dymek2-sheet0.png",
		"images/dymki-sheet0.png",
		"images/dymki-sheet1.png",
		"images/ded-sheet0.png",
		"images/1_2-sheet0.png",
		"images/1_2-sheet1.png",
		"images/dedklapa-sheet0.png",
		"images/dedklapa-sheet1.png",
		"images/dedklapa-sheet2.png",
		"images/prawabad-sheet0.png",
		"images/prawabad-sheet1.png",
		"images/prawabad-sheet2.png",
		"images/1_4-sheet0.png",
		"images/1_4-sheet1.png",
		"images/ded2-sheet0.png",
		"images/zrzutekranu-sheet0.png",
		"images/2lokaciapodworkoprzedlazienka-sheet0.png",
		"images/2lokaciapodworkoprzedlazienka-sheet1.png",
		"images/2lokaciapodworkoprzedlazienka-sheet2.png",
		"images/menu-sheet0.png",
		"images/19105233_1383636758393476_944283944_o-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/sprite5-sheet1.png",
		"images/sprite5-sheet2.png",
		"images/rustkolizje-sheet0.png",
		"media/czajnik.m4a",
		"media/czajnik.ogg",
		"media/przybija.m4a",
		"media/przybija.ogg",
		"media/sprezyny.m4a",
		"media/sprezyny.ogg",
		"media/toster.m4a",
		"media/toster.ogg",
		"media/przebija.m4a",
		"media/przebija.ogg",
		"media/sfx - cieszy sie.ogg",
		"media/sfx - eva krok 1.ogg",
		"media/sfx - eva krok 2.ogg",
		"media/sfx - kiwa glowa 1.ogg",
		"media/sfx - kiwa glowa 2.ogg",
		"media/sfx - mlotek szybko.ogg",
		"media/sfx - mlotek wolno.ogg",
		"media/sfx - polozyc 1.ogg",
		"media/sfx - ruch robota 1.ogg",
		"media/sfx - ruch robota 2.ogg",
		"media/sfx - rust krok 1.ogg",
		"media/sfx - rust krok 2.ogg",
		"media/sfx - trzesienie.ogg",
		"media/sfx - rust i eva gra wstepna.ogg",
		"media/sfx - polozyc 2.ogg",
		"media/02 dialog rust eva.m4a",
		"media/02 dialog rust eva.ogg",
		"media/03 kiwa glowa.m4a",
		"media/03 kiwa glowa.ogg",
		"media/04 podaje.m4a",
		"media/04 podaje.ogg",
		"media/05 kladzie.m4a",
		"media/05 kladzie.ogg",
		"media/06 kladzie.m4a",
		"media/06 kladzie.ogg",
		"media/07 uderza mlotkiem.m4a",
		"media/07 uderza mlotkiem.ogg",
		"media/08 sklada elementy.m4a",
		"media/08 sklada elementy.ogg",
		"media/09 uderza mlotkiem lekko.m4a",
		"media/09 uderza mlotkiem lekko.ogg",
		"media/10 ric wstaje.m4a",
		"media/10 ric wstaje.ogg",
		"media/11 serce evy.m4a",
		"media/11 serce evy.ogg",
		"media/12 rust sie cieszy.m4a",
		"media/12 rust sie cieszy.ogg",
		"media/13 halas i trzesienie.m4a",
		"media/13 halas i trzesienie.ogg",
		"media/14 ded idzie.m4a",
		"media/14 ded idzie.ogg",
		"media/15 bad schyla sie.m4a",
		"media/15 bad schyla sie.ogg",
		"media/16 bad uderza.m4a",
		"media/16 bad uderza.ogg",
		"media/17 ded upada.m4a",
		"media/17 ded upada.ogg",
		"media/18 bad lapie podnosi.m4a",
		"media/18 bad lapie podnosi.ogg",
		"media/19 bad obraca deda.m4a",
		"media/19 bad obraca deda.ogg",
		"media/20 klapka otwiera.m4a",
		"media/20 klapka otwiera.ogg",
		"media/21 bad bierze.m4a",
		"media/21 bad bierze.ogg",
		"media/22 bad zabiera.m4a",
		"media/22 bad zabiera.ogg",
		"media/23 maly obiekt upada.m4a",
		"media/23 maly obiekt upada.ogg",
		"media/24 bad rzuca.m4a",
		"media/24 bad rzuca.ogg",
		"media/sfx - cieszy sie.m4a",
		"media/sfx - eva krok 1.m4a",
		"media/sfx - eva krok 2.m4a",
		"media/sfx - kiwa glowa 1.m4a",
		"media/sfx - kiwa glowa 2.m4a",
		"media/sfx - mlotek szybko.m4a",
		"media/sfx - mlotek wolno.m4a",
		"media/sfx - polozyc 1.m4a",
		"media/sfx - polozyc 2.m4a",
		"media/sfx - ruch robota 1.m4a",
		"media/sfx - ruch robota 2.m4a",
		"media/sfx - rust i eva gra wstepna.m4a",
		"media/sfx - trzesienie.m4a",
		"media/glowaskok.ogg",
		"media/grzmot.ogg",
		"media/kreciglowa.ogg",
		"media/grzmot2.ogg",
		"media/kropla.ogg",
		"media/kropla.m4a",
		"media/zebatka.ogg",
		"media/wkrecaswojaglowe.ogg",
		"media/zwarcie.ogg",
		"media/zwarcie2.ogg",
		"media/zwarcie5.ogg",
		"media/beep 1.m4a",
		"media/beep 1.ogg",
		"media/beep 2.m4a",
		"media/beep 2.ogg",
		"media/beep aetrim1489480984501.m4a",
		"media/beep aetrim1489480984501.ogg",
		"media/beep dobrze.m4a",
		"media/beep dobrze.ogg",
		"media/beep tlo.m4a",
		"media/beep tlo.ogg",
		"media/beep.m4a",
		"media/beep.ogg",
		"media/beepsygnal.m4a",
		"media/beepsygnal.ogg",
		"media/bezpieczik.m4a",
		"media/bezpieczik.ogg",
		"media/bob chodzi.m4a",
		"media/bob chodzi.ogg",
		"media/brrr.m4a",
		"media/brrr.ogg",
		"media/chodzi 1.m4a",
		"media/chodzi 1.ogg",
		"media/chodzi 2.m4a",
		"media/chodzi 2.ogg",
		"media/ciągnie przewraca.m4a",
		"media/ciągnie przewraca.ogg",
		"media/ciągnie za szafke.m4a",
		"media/ciągnie za szafke.ogg",
		"media/ciągnie zamkniete.m4a",
		"media/ciągnie zamkniete.ogg",
		"media/daje bierze.m4a",
		"media/daje bierze.ogg",
		"media/daje.m4a",
		"media/daje.ogg",
		"media/glowaskacze.m4a",
		"media/glowaskacze.ogg",
		"media/grzmot.m4a",
		"media/grzmot2.m4a",
		"media/minigra kod koniec.m4a",
		"media/minigra kod koniec.ogg",
		"media/nie.m4a",
		"media/nie.ogg",
		"media/otwiera.m4a",
		"media/otwiera.ogg",
		"media/otwieraa.m4a",
		"media/otwieraa.ogg",
		"media/otwierab.m4a",
		"media/otwierab.ogg",
		"media/przepycha.m4a",
		"media/przepycha.ogg",
		"media/przysłać bob.m4a",
		"media/przysłać bob.ogg",
		"media/puka.m4a",
		"media/puka.ogg",
		"media/schyla przy wc.m4a",
		"media/schyla przy wc.ogg",
		"media/signal.m4a",
		"media/signal.ogg",
		"media/wkreca głowe.m4a",
		"media/wkreca głowe.ogg",
		"media/wkreca2.m4a",
		"media/wkreca2.ogg",
		"media/wyrywa drzwiczki.m4a",
		"media/wyrywa drzwiczki.ogg",
		"media/występuje smieci.m4a",
		"media/występuje smieci.ogg",
		"media/zamkniete1.m4a",
		"media/zamkniete1.ogg",
		"media/zamyka.m4a",
		"media/zamyka.ogg",
		"media/zebatki.m4a",
		"media/zebatki.ogg",
		"media/zebatki2.m4a",
		"media/zebatki2.ogg",
		"media/zwarcie.m4a",
		"media/zwarcie2.m4a",
		"media/zwarcie5.m4a",
		"media/zwarcie7.m4a",
		"media/zwarcie7.ogg",
		"media/sfx - rust krok 1.m4a",
		"media/sfx - rust krok 2.m4a",
		"media/chod.m4a",
		"media/chod.ogg",
		"media/lvl1.ogg",
		"media/futurust - ghost in the machine-4.m4a",
		"media/futurust - ghost in the machine-4.ogg",
		"media/sfx - dzungla.ogg",
		"media/sfx - podworko.ogg",
		"media/intro-muzyka-demo.m4a",
		"media/intro-muzyka-demo.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}