{
	"version": 1488145915,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/target-sheet0.png",
		"images/rustmov-sheet0.png",
		"images/rustanim-sheet0.png",
		"images/rustanim-sheet1.png",
		"images/rustanim-sheet2.png",
		"images/strefachodzenia-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/restartbutton-sheet0.png",
		"images/restartbutton-sheet1.png",
		"images/rozjasnienie.png",
		"images/kamera-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite2-sheet1.png",
		"images/sprite2-sheet2.png",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}