{
	"version": 1496010974,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/rustanim-sheet0.png",
		"images/rustanim-sheet1.png",
		"images/rustanim-sheet2.png",
		"images/rustmov-sheet0.png",
		"images/bob-sheet0.png",
		"images/bob-sheet1.png",
		"images/bob-sheet2.png",
		"images/bob-sheet3.png",
		"images/guzikeq-sheet0.png",
		"images/sprite22-sheet0.png",
		"images/sprite22-sheet1.png",
		"images/podpstrzalka-sheet0.png",
		"images/podpstrzalka-sheet1.png",
		"images/kropelka-sheet0.png",
		"images/kropelka-sheet1.png",
		"images/odlamki-sheet0.png",
		"images/odlamki2-sheet0.png",
		"images/odlamki2-sheet1.png",
		"images/drzwi-sheet0.png",
		"images/sprite36-sheet0.png",
		"images/sprite34-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite-sheet1.png",
		"images/sprite24-sheet0.png",
		"images/sprite29-sheet0.png",
		"images/sprite32-sheet0.png",
		"images/sprite56-sheet0.png",
		"images/sprite56-sheet1.png",
		"images/wiatraczek-sheet0.png",
		"images/wiatraczek-sheet1.png",
		"images/sprite2-sheet0.png",
		"images/sprite2-sheet1.png",
		"images/sprite10-sheet0.png",
		"images/kolkropla-sheet0.png",
		"images/kolkropla-sheet1.png",
		"images/glowabad-sheet0.png",
		"images/nogibad-sheet0.png",
		"images/nogibad-sheet1.png",
		"images/klapabad-sheet0.png",
		"images/klapabad-sheet1.png",
		"images/introtlo-sheet0.png",
		"images/introtlo-sheet1.png",
		"images/1_-sheet0.png",
		"images/1_-sheet1.png",
		"images/introeva-sheet0.png",
		"images/introrust-sheet0.png",
		"images/ricintrolezy-sheet0.png",
		"images/ricintrolezy-sheet1.png",
		"images/ricintrolezy-sheet2.png",
		"images/sterowiec-sheet0.png",
		"images/tulow_-sheet0.png",
		"images/toster-sheet0.png",
		"images/toster-sheet1.png",
		"images/reka-sheet0.png",
		"images/reka2-sheet0.png",
		"images/restartbutton-sheet0.png",
		"images/restartbutton-sheet1.png",
		"images/kamera-sheet0.png",
		"images/guzikmenu-sheet0.png",
		"images/przyciemnienie.png",
		"images/target-sheet0.png",
		"images/strefachodzenia-sheet0.png",
		"images/sprite9-sheet0.png",
		"images/sprite11-sheet0.png",
		"images/sprite12-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/sprite21-sheet0.png",
		"images/trescdymek-sheet0.png",
		"images/trescdymek-sheet1.png",
		"images/podp1-sheet0.png",
		"images/podp1-sheet1.png",
		"images/sprite23-sheet0.png",
		"images/items-sheet0.png",
		"images/eqitem-sheet0.png",
		"images/sprite31-sheet0.png",
		"images/sprite31-sheet1.png",
		"images/sprite33-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/sprite4-sheet1.png",
		"images/sprite4-sheet2.png",
		"images/sprite17-sheet0.png",
		"images/sprite17-sheet1.png",
		"images/sprite19-sheet0.png",
		"images/sprite19-sheet1.png",
		"images/sprite20-sheet0.png",
		"images/sprite27-sheet0.png",
		"images/sprite35-sheet0.png",
		"images/sprite35-sheet1.png",
		"images/sprite37-sheet0.png",
		"images/sprite37-sheet1.png",
		"images/sprite37-sheet2.png",
		"images/sprite37-sheet3.png",
		"images/sprite37-sheet4.png",
		"images/sprite37-sheet5.png",
		"images/sprite37-sheet6.png",
		"images/sprite37-sheet7.png",
		"images/sprite38-sheet0.png",
		"images/sprite39-sheet0.png",
		"images/sprite39-sheet1.png",
		"images/sprite41-sheet0.png",
		"images/sprite42-sheet0.png",
		"images/sprite42-sheet1.png",
		"images/sprite43-sheet0.png",
		"images/sprite44-sheet0.png",
		"images/sprite45-sheet0.png",
		"images/sprite45-sheet1.png",
		"images/sprite46-sheet0.png",
		"images/sprite46-sheet1.png",
		"images/sprite48-sheet0.png",
		"images/sprite48-sheet1.png",
		"images/sprite49-sheet0.png",
		"images/sprite50-sheet0.png",
		"images/sprite54-sheet0.png",
		"images/sprite54-sheet1.png",
		"images/sprite55-sheet0.png",
		"images/sprite55-sheet1.png",
		"images/sprite55-sheet2.png",
		"images/drzwi2-sheet0.png",
		"images/dymek-sheet0.png",
		"images/dymek2-sheet0.png",
		"images/dymki-sheet0.png",
		"images/dymki-sheet1.png",
		"images/badkorpus-sheet0.png",
		"images/ded-sheet0.png",
		"images/1_2-sheet0.png",
		"images/1_2-sheet1.png",
		"images/dedklapa-sheet0.png",
		"images/dedklapa-sheet1.png",
		"images/dedklapa-sheet2.png",
		"images/prawabad-sheet0.png",
		"images/prawabad-sheet1.png",
		"images/prawabad-sheet2.png",
		"images/1_4-sheet0.png",
		"images/1_4-sheet1.png",
		"images/ded2-sheet0.png",
		"media/czajnik.m4a",
		"media/czajnik.ogg",
		"media/przybija.m4a",
		"media/przybija.ogg",
		"media/sprezyny.m4a",
		"media/sprezyny.ogg",
		"media/toster.m4a",
		"media/toster.ogg",
		"media/przebija.m4a",
		"media/przebija.ogg",
		"media/sfx - cieszy sie.ogg",
		"media/sfx - eva krok 1.ogg",
		"media/sfx - eva krok 2.ogg",
		"media/sfx - kiwa glowa 1.ogg",
		"media/sfx - kiwa glowa 2.ogg",
		"media/sfx - mlotek szybko.ogg",
		"media/sfx - mlotek wolno.ogg",
		"media/sfx - polozyc 1.ogg",
		"media/sfx - polozyc 2.ogg",
		"media/sfx - ruch robota 1.ogg",
		"media/sfx - ruch robota 2.ogg",
		"media/sfx - rust krok 1.ogg",
		"media/sfx - rust krok 2.ogg",
		"media/sfx - trzesienie.ogg",
		"media/grzmot.ogg",
		"media/grzmot2.ogg",
		"media/zwarcie.ogg",
		"media/zwarcie2.ogg",
		"media/zwarcie5.ogg",
		"media/gs.ogg",
		"media/wg.ogg",
		"media/n.ogg",
		"media/kropla.m4a",
		"media/kropla.ogg",
		"media/lvl1.ogg",
		"media/futurust - ghost in the machine-4.m4a",
		"media/futurust - ghost in the machine-4.ogg",
		"media/sfx - dzungla.ogg",
		"media/sfx - podworko.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}