{
	"version": 1493749965,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/bg-sheet0.png",
		"images/player-sheet0.png",
		"images/player-sheet1.png",
		"images/coin-sheet0.png",
		"images/sprite-sheet0.png",
		"images/bg2-sheet0.png",
		"images/spawner-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/bg3-sheet0.png",
		"images/tiledbackground.png",
		"images/bg4-sheet0.png",
		"images/bg4-sheet1.png",
		"images/sprite2-sheet0.png",
		"images/wood-sheet0.png",
		"images/sprite8-sheet0.png",
		"images/coin2-sheet0.png",
		"images/spritefont.png",
		"images/arrowsprite-sheet0.png",
		"images/arrowsprite-sheet1.png",
		"images/arrowsprite-sheet2.png",
		"media/common_coins_001.m4a",
		"media/common_coins_001.ogg",
		"media/flash point hit_04.m4a",
		"media/flash point hit_04.ogg",
		"media/bubble1 (2).m4a",
		"media/bubble1 (2).ogg",
		"media/bubble1 (3).m4a",
		"media/bubble1 (3).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"channel.html"
	]
}