{
	"version": 1491326807,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/dash-sheet0.png",
		"images/sok-sheet0.png",
		"images/particles.png",
		"images/arbuz-sheet0.png",
		"images/cietyarbuz-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/arb-sheet0.png",
		"images/arbzzx-sheet0.png",
		"images/tiledbackground.png",
		"images/plama-sheet0.png",
		"images/tiledbackground2.jpg",
		"images/blood-sheet0.png",
		"images/blood2-sheet0.png",
		"images/startdroida-sheet0.png",
		"media/ciecie.ogg",
		"media/ciecie2.ogg",
		"media/cięcie3.ogg",
		"media/critical anime.ogg",
		"media/powolne zamachniecia.ogg",
		"media/szybkie zamachniecia.ogg",
		"media/uderzenie o metal.ogg",
		"media/zamachniecie króciutkie.ogg",
		"media/zamachniecie krótkie.ogg",
		"media/zamachniecie.ogg",
		"media/zamachniecie2.ogg",
		"media/sok.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}