{
	"version": 1496564985,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/playerwaclaw-sheet0.png",
		"images/playerwaclaw-sheet1.png",
		"images/bron-sheet0.png",
		"images/pocisk-sheet0.png",
		"images/caracel-sheet0.png",
		"images/player2-sheet0.png",
		"images/player2-sheet1.png",
		"images/player2-sheet2.png",
		"images/34_drzewko-sheet0.png",
		"images/misiewiczglowa-sheet0.png",
		"images/misiewiczglowa-sheet1.png",
		"images/misiewicz-sheet0.png",
		"images/m1garandrifle-sheet0.png",
		"images/waclawglowa-sheet0.png",
		"images/waclawglowa-sheet1.png",
		"images/triggger-sheet0.png",
		"images/dymek-sheet0.png",
		"images/dymek-sheet1.png",
		"images/paisagemnaturalcampoverde-sheet0.png",
		"images/ep2_exp8_-sheet0.png",
		"images/ep2_exp8_-sheet1.png",
		"images/ep2_exp8_-sheet2.png",
		"images/oorder-sheet0.png",
		"images/misiewiczglowa2-sheet0.png",
		"images/dymek2-sheet0.png",
		"images/dymek2-sheet1.png",
		"images/pluie-sheet0.png",
		"images/pluie-sheet1.png",
		"images/pluie-sheet2.png",
		"images/z20902223vcaracal-sheet0.png",
		"images/pngpixcomexplosionpngimage-sheet0.png",
		"images/andrzejdudananartach_-sheet0.png",
		"images/8640717jaroslawkaczynskiwsejmie-sheet0.png",
		"images/tojawykonczylem-sheet0.png",
		"images/glownarolawacek-sheet0.png",
		"images/zolnierz-sheet0.png",
		"images/zolnierz-sheet1.png",
		"images/pict_-sheet0.png",
		"images/parasol-sheet0.png",
		"images/fogpnghd-sheet0.png",
		"images/podkurzaczocynkowanyzchlodnicamaleotwory-sheet0.png",
		"media/step2.m4a",
		"media/step2.ogg",
		"media/052-cannon01.m4a",
		"media/052-cannon01.ogg",
		"media/ricochet_metal_01_001.m4a",
		"media/ricochet_metal_01_001.ogg",
		"media/dziekuje wacku.m4a",
		"media/dziekuje wacku.ogg",
		"media/reload_001.m4a",
		"media/reload_001.ogg",
		"media/heli_001.m4a",
		"media/heli_001.ogg",
		"media/explode1_001.m4a",
		"media/explode1_001.ogg",
		"media/fanfare (2).m4a",
		"media/fanfare (2).ogg",
		"media/new bonus 2.m4a",
		"media/new bonus 2.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}