{
	"version": 1487113932,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/twarzewczerwonymsercuwektor-sheet0.png",
		"images/tablicapytania-sheet0.png",
		"images/karta1-sheet0.png",
		"images/karta1-sheet1.png",
		"images/karta1-sheet2.png",
		"images/finalimage-sheet0.png",
		"images/button-sheet0.png",
		"images/kartabg-sheet0.png",
		"images/dogry-sheet0.png",
		"images/arrowdown-sheet0.png",
		"images/pytanie-sheet0.png",
		"media/message ping x2.m4a",
		"media/message ping x2.ogg",
		"media/simpe cute alert 227.m4a",
		"media/simpe cute alert 227.ogg",
		"media/simpe cute alert 15_001.m4a",
		"media/simpe cute alert 15_001.ogg",
		"media/simple digital connection 9.m4a",
		"media/simple digital connection 9.ogg",
		"media/card.m4a",
		"media/card.ogg",
		"media/cardputdown.m4a",
		"media/cardputdown.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"animate.min.css"
	]
}