{
	"version": 1493707534,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/1player-sheet0.png",
		"images/1player-sheet1.png",
		"images/1player-sheet2.png",
		"images/cel-sheet0.png",
		"images/camera-sheet0.png",
		"images/slot-sheet0.png",
		"images/slot-sheet1.png",
		"images/slot-sheet2.png",
		"images/item-sheet0.png",
		"images/item-sheet1.png",
		"images/item-sheet2.png",
		"images/stats.png",
		"images/cooltext-sheet0.png",
		"images/grabarea-sheet0.png",
		"images/cooltextinv-sheet0.png",
		"images/hpbar-sheet0.png",
		"images/lvupmessage.png",
		"images/aim-sheet0.png",
		"images/aim-sheet1.png",
		"images/aim-sheet2.png",
		"images/view-sheet0.png",
		"images/eatuse-sheet0.png",
		"images/eatuse-sheet1.png",
		"images/eatuse-sheet2.png",
		"images/slotweapon-sheet0.png",
		"images/slotweapon-sheet1.png",
		"images/flash-sheet0.png",
		"images/waran-sheet0.png",
		"images/grabarea2-sheet0.png",
		"images/slotarmor-sheet0.png",
		"images/cel2-sheet0.png",
		"images/hitanimation-sheet0.png",
		"images/slotpistol-sheet0.png",
		"images/slotpistol-sheet1.png",
		"images/slotpistol-sheet2.png",
		"images/bullethit-sheet0.png",
		"images/bullethit-sheet1.png",
		"images/slotweapon2-sheet0.png",
		"images/arrow-sheet0.png",
		"images/slothead-sheet0.png",
		"images/slothead-sheet1.png",
		"images/slotboots-sheet0.png",
		"images/barwaran-sheet0.png",
		"images/xptext-sheet0.png",
		"images/bulletpl-sheet0.png",
		"images/tilemap1.png",
		"images/cam-sheet0.png",
		"media/grab.m4a",
		"media/grab.ogg",
		"media/trigger_click_001.m4a",
		"media/trigger_click_001.ogg",
		"media/lvup.m4a",
		"media/lvup.ogg",
		"media/drinking water.m4a",
		"media/drinking water.ogg",
		"media/odetkanie butelki.m4a",
		"media/odetkanie butelki.ogg",
		"media/eat.m4a",
		"media/eat.ogg",
		"media/equip1wep.m4a",
		"media/equip1wep.ogg",
		"media/equip2cloth.m4a",
		"media/equip2cloth.ogg",
		"media/knife_hit3.m4a",
		"media/knife_hit3.ogg",
		"media/pistol_fire2.m4a",
		"media/pistol_fire2.ogg",
		"media/drop armor.m4a",
		"media/drop armor.ogg",
		"media/drop pistol.m4a",
		"media/drop pistol.ogg",
		"media/a metal weapon is dropped.m4a",
		"media/a metal weapon is dropped.ogg",
		"media/bow.ogg",
		"media/bandadge.m4a",
		"media/bandadge.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"pathfind.js"
	]
}