{
	"version": 1488201775,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/bike-sheet0.png",
		"images/rearwheel-sheet0.png",
		"images/frontwheel-sheet0.png",
		"images/shaft2-sheet0.png",
		"images/shaft-sheet0.png",
		"images/ground.png",
		"images/sprite-sheet0.png",
		"images/player_helmet-sheet0.png",
		"images/player_helmet-sheet1.png",
		"images/player_thighs-sheet0.png",
		"images/player_body-sheet0.png",
		"images/player_hip-sheet0.png",
		"images/player_leg-sheet0.png",
		"images/player_hand-sheet0.png",
		"images/sprite8-sheet0.png",
		"images/landscape.png",
		"images/awan.png",
		"images/touch_accelerate-sheet0.png",
		"images/touch_accelerate-sheet1.png",
		"images/touch_brakereverse-sheet0.png",
		"images/touch_brakereverse-sheet1.png",
		"images/touch_up-sheet0.png",
		"images/touch_down-sheet0.png",
		"images/controller_border-sheet0.png",
		"images/block-sheet0.png",
		"images/camerascroll-sheet0.png",
		"images/bike_front-sheet0.png",
		"images/bike_rear-sheet0.png",
		"images/damage-sheet0.png",
		"images/asap_break-sheet0.png",
		"images/break-sheet0.png",
		"images/reverse_leg-sheet0.png",
		"images/reverse_leg-sheet1.png",
		"images/reverse_leg-sheet2.png",
		"images/touch_break_rear-sheet0.png",
		"images/touch_break_front-sheet0.png",
		"images/touch_break_front-sheet1.png",
		"images/bird-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/spritefont.png",
		"media/motor idle.m4a",
		"media/motor idle.ogg",
		"media/motor gaz (2.1).m4a",
		"media/motor gaz (2.1).ogg",
		"media/motor gaz (start).m4a",
		"media/motor gaz (start).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}