{
	"version": 1486567926,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/celownik-sheet0.png",
		"images/tiledbackground.png",
		"images/bullet-sheet0.png",
		"images/player-sheet0.png",
		"images/tiledbackground2.png",
		"images/fence_idea-sheet0.png",
		"images/kurzexp-sheet0.png",
		"images/kurzexp-sheet1.png",
		"images/kropka-sheet0.png",
		"images/particles.png",
		"images/human-sheet0.png",
		"images/human-sheet1.png",
		"images/corpse-sheet0.png",
		"images/my_pixel_cars_collection_by_poke_yoshi-sheet0.png",
		"images/my_pixel_cars_collection_by_poke_yoshi-sheet1.png",
		"images/truck-sheet0.png",
		"images/zrzutekranu-sheet0.png",
		"images/tarcza-sheet0.png",
		"images/tarcza2-sheet0.png",
		"images/dirthit_2-sheet0.png",
		"images/dirthit_2-sheet1.png",
		"images/dirthit_2-sheet2.png",
		"images/lens-sheet0.png",
		"images/human2-sheet0.png",
		"images/sprite-sheet0.png",
		"images/firesmall-sheet0.png",
		"images/firesmall-sheet1.png",
		"images/firesmall-sheet2.png",
		"images/firemedium-sheet0.png",
		"images/firemedium-sheet1.png",
		"images/firemedium-sheet2.png",
		"images/firehuman-sheet0.png",
		"images/firehuman-sheet1.png",
		"images/sprite2-sheet0.png",
		"images/sprite2-sheet1.png",
		"images/sprite2-sheet2.png",
		"media/gun.m4a",
		"media/gun.ogg",
		"media/hurtfemale.m4a",
		"media/hurtfemale.ogg",
		"media/hurtmale.m4a",
		"media/hurtmale.ogg",
		"media/hurtmale2.m4a",
		"media/hurtmale2.ogg",
		"media/hurtfemale2.m4a",
		"media/hurtfemale2.ogg",
		"media/hurtfemale3.m4a",
		"media/hurtfemale3.ogg",
		"media/mhit (1).m4a",
		"media/mhit (1).ogg",
		"media/mhit (2).m4a",
		"media/mhit (2).ogg",
		"media/mhit (3).m4a",
		"media/mhit (3).ogg",
		"media/mhit (4).m4a",
		"media/mhit (4).ogg",
		"media/mhit (5).m4a",
		"media/mhit (5).ogg",
		"media/mhit (6).m4a",
		"media/mhit (6).ogg",
		"media/mhit (7).m4a",
		"media/mhit (7).ogg",
		"media/mhit (8).m4a",
		"media/mhit (8).ogg",
		"media/allahu akbar.m4a",
		"media/allahu akbar.ogg",
		"media/akbarstart.m4a",
		"media/akbarstart.ogg",
		"media/grenadeexplo.m4a",
		"media/grenadeexplo.ogg",
		"media/manscream (1).m4a",
		"media/manscream (1).ogg",
		"media/manscream (2).m4a",
		"media/manscream (2).ogg",
		"media/womanscream (1).m4a",
		"media/womanscream (1).ogg",
		"media/womanscream (2).m4a",
		"media/womanscream (2).ogg",
		"media/fleshfall.m4a",
		"media/fleshfall.ogg",
		"media/womanscream (3).m4a",
		"media/womanscream (3).ogg",
		"media/womanscream (4).m4a",
		"media/womanscream (4).ogg",
		"media/manscream (3).m4a",
		"media/manscream (3).ogg",
		"media/manscream (4).m4a",
		"media/manscream (4).ogg",
		"media/manscream (5).m4a",
		"media/manscream (5).ogg",
		"media/manscream (6).m4a",
		"media/manscream (6).ogg",
		"media/heat.m4a",
		"media/heat.ogg",
		"media/1lv_001.m4a",
		"media/1lv_001.ogg",
		"media/afganistan.m4a",
		"media/afganistan.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"firebase.js"
	]
}